[DEFAULT]
# raw fts input
fts_input=RAW_INPUT_FTS
#FTS

fts_classified=FTS_BRIGHT_STARS,FTS_DIM_STARS,FTS_NO_STARS

# Brightness thresholds
fwhm=3.0
low_threshold=5.0
high_threshold=10.0

dry_run=true

# JSON (predictions summary ) input for verification
# It is expected that prediction run produces JSON classification output
predicted_json=OUTPUTS/out_fts_dict_pt.json

# astropy calculation output:
calculated_json=OUTPUTS/calc_fts_dict.json
calculation_output=OUTPUTS/CALCULATION_FTS
unified_csv=OUTPUTS/unified_fts.csv